# Generated by Django 3.1.2 on 2020-11-01 01:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, verbose_name='User Name')),
                ('password', models.CharField(max_length=50, verbose_name='User Password')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.CharField(max_length=5, primary_key=True, serialize=False, verbose_name='Department ID')),
                ('name', models.CharField(max_length=50, verbose_name='Department Name')),
                ('phone', models.CharField(max_length=15, null=True, verbose_name='Phone Number')),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.CharField(max_length=5, primary_key=True, serialize=False, verbose_name='Position ID')),
                ('name', models.CharField(max_length=50, verbose_name='Position Name')),
            ],
        ),
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('salary_grade', models.IntegerField(primary_key=True, serialize=False, verbose_name='Salary Grade')),
                ('basic_salary', models.IntegerField(verbose_name='Basic Salary')),
                ('salary_coefficient', models.IntegerField(verbose_name='Salary Coefficient')),
                ('allowance_coefficient', models.IntegerField(verbose_name='Allowance Coefficient')),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Full Name')),
                ('ethnic_group', models.CharField(max_length=20, verbose_name='Ethnic Group')),
                ('gender', models.CharField(max_length=7, verbose_name='Gender')),
                ('address', models.CharField(max_length=200, verbose_name='Address')),
                ('dob', models.DateField(verbose_name='Date of Birth')),
                ('phone', models.CharField(max_length=15, verbose_name='Phone Number')),
                ('department_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MYAPP.department')),
                ('position_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MYAPP.position')),
                ('salary_grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MYAPP.salary')),
            ],
        ),
    ]
